name: test - TDLOG

on: [pull_request, push]

jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: tdlog-tp
        environment-file: environment.yml
        python-version: "3.10"
        miniconda-version: "latest"
        auto-update-conda: true
        auto-activate-base: false
    - name: List packages
      run: |
        conda list
    - name: Format with black
      if: always()
      run: |
        black --check --diff .
    - name: Lint with flake8
      if: always()
      run: |
        flake8 .
